### ISSUE TITLE
Clicking issue

### ISSUE THREAD

**Issue by GS-Viduus** [pltrant/GSL-Editor#15]
So, I'm starting to notice that scripts are getting reverted to older versions.   As an example, I'll have pushed changes to the live instances to fix something, and a few weeks/months later notice people complaining about the same problem.

I suspect it's a result of people clicking a mm link in a script and the editor is opening their outdated local copy instead of downloading a new version from dev.  I've switched to habitually using the download button when I open scripts and stop using the click functionality.  I was thinking about how to fix it and it should probably check the dev instance version for a timestamp, and if that's older than your local copy default to the local.  Otherwise grab an updated one from the server.

**Comment by pltrant** [comment]
Currently, the extension will check to see if you already have a local copy of the file and if so, just open it directly.  If you don't have a local copy, it will download it from the server.  @anshou, @GS-Naijin thoughts on always just doing the latter?

**Comment by GS-Naijin** [comment]
I don't think that's safe to do and risks overwriting edits locally when working on systems. This would have definitely hosed me during the PSM update due to all the various scripts interacting with each other.

**Comment by anshou** [comment]
What Kyle said.  Fixing a bad script upload to Dev isn't that much effort
at this point with GitHub but recovering a GM's local work is unlikely in
most cases.

We can have that code check the script header on the server and compare it
to a cached header locally and make a decision based on that and the local
modification time in the filesystem.  If you haven't edited the file
locally since you downloaded it and it is newer on the server, it could be
downloaded.  If you have edited it locally, you would be prompted to make a
choice (with a don't remind me again for this script option?)

**Comment by abirmingham** [comment]
> We can have that code check the script header on the server and compare it
> to a cached header locally and make a decision based on that and the local
> modification time in the filesystem.  If you haven't edited the file
> locally since you downloaded it and it is newer on the server, it could be
> downloaded.  If you have edited it locally, you would be prompted to make a
> choice (with a don't remind me again for this script option?)

This seems reasonable, either using the mod time or a checksum.

I also wonder if the extension should do more to indicate that your local copy is out of sync. I'll give this some more thought.
